// Generated by gencpp from file beginner_tutorials/caltheta.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CALTHETA_H
#define BEGINNER_TUTORIALS_MESSAGE_CALTHETA_H

#include <ros/service_traits.h>


#include <beginner_tutorials/calthetaRequest.h>
#include <beginner_tutorials/calthetaResponse.h>


namespace beginner_tutorials
{

struct caltheta
{

typedef calthetaRequest Request;
typedef calthetaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct caltheta
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::caltheta > {
  static const char* value()
  {
    return "025ad305c8a2a52a6619bcbaadf0ed73";
  }

  static const char* value(const ::beginner_tutorials::caltheta&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::caltheta > {
  static const char* value()
  {
    return "beginner_tutorials/caltheta";
  }

  static const char* value(const ::beginner_tutorials::caltheta&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::calthetaRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::caltheta > 
template<>
struct MD5Sum< ::beginner_tutorials::calthetaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::caltheta >::value();
  }
  static const char* value(const ::beginner_tutorials::calthetaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::calthetaRequest> should match 
// service_traits::DataType< ::beginner_tutorials::caltheta > 
template<>
struct DataType< ::beginner_tutorials::calthetaRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::caltheta >::value();
  }
  static const char* value(const ::beginner_tutorials::calthetaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::calthetaResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::caltheta > 
template<>
struct MD5Sum< ::beginner_tutorials::calthetaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::caltheta >::value();
  }
  static const char* value(const ::beginner_tutorials::calthetaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::calthetaResponse> should match 
// service_traits::DataType< ::beginner_tutorials::caltheta > 
template<>
struct DataType< ::beginner_tutorials::calthetaResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::caltheta >::value();
  }
  static const char* value(const ::beginner_tutorials::calthetaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CALTHETA_H
