// Generated by gencpp from file beginner_tutorials/testResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TESTRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_TESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct testResponse_
{
  typedef testResponse_<ContainerAllocator> Type;

  testResponse_()
    : responsenum()  {
    }
  testResponse_(const ContainerAllocator& _alloc)
    : responsenum(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _responsenum_type;
  _responsenum_type responsenum;




  typedef boost::shared_ptr< ::beginner_tutorials::testResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::testResponse_<ContainerAllocator> const> ConstPtr;

}; // struct testResponse_

typedef ::beginner_tutorials::testResponse_<std::allocator<void> > testResponse;

typedef boost::shared_ptr< ::beginner_tutorials::testResponse > testResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::testResponse const> testResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::testResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::testResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/chengda/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::testResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::testResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::testResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::testResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::testResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::testResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "302dd7ef7fe0bbc22f00da78e17d0aad";
  }

  static const char* value(const ::beginner_tutorials::testResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x302dd7ef7fe0bbc2ULL;
  static const uint64_t static_value2 = 0x2f00da78e17d0aadULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/testResponse";
  }

  static const char* value(const ::beginner_tutorials::testResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::testResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string responsenum\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::testResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::testResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.responsenum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct testResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::testResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::testResponse_<ContainerAllocator>& v)
  {
    s << indent << "responsenum: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.responsenum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TESTRESPONSE_H
